### ISSUE TITLE
Several pictures

### ISSUE THREAD

**Issue by Digidani** [moy/piwigo-random#1]
I am using the serveral pictures option and want to know if it´s possible to get some space between the pictures? Now my four pictures looks so [][][][]  What I want: [] [] [] []

**Comment by moy** [comment]
Do you have an example on a public site?

**Comment by Digidani** [comment]
No, the site isn´t public at the moment. But you can look at your demo site:  http://matthieu-moy.fr/piwigo-random/piwigo-random-demo.html  -> "Several images at a time"   There is also no space between the pictures.

**Comment by moy** [comment]
Here you are, I've just added an example. Just change `margin-left:` and `margin-right:` in the CSS. In my example I use the name of the `<div>` containing the image to apply the CSS to these images only, but any CSS selector will work.
