### ISSUE TITLE
Piwigo very slow after opening a random picture from extern phpbb3

### ISSUE THREAD

**Issue by Digidani** [moy/piwigo-random#3]
Click at a random image in my forum https://www.dresdens-harter-kern.de/phpbb3/portal let open piwigo very slow. Opening the same picture in piwigo directly all is fine.

What happened here? Why is random image slow, the gallery itself not? Is there any option to use?

**Comment by moy** [comment]
I tried opening a URL directly (https://www.dhk-galerie.de/dhkfotos/picture.php?/6984) and I get the same slowness (including in a private window and with a different browser). Apparently there's an issue with a piece of JavaScript somewhere. Piwigo-random is just generating a very basic link to the image, it doesn't do anything on the target page. Everything seems to indicate that Piwigo-random is not the guilty one here, but do re-open if you have any element suggesting that it is.
